version: "3.8"
services:
  vault-server:
    image: vault:1.10.0
    container_name: spring-cloud-config-demo-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    cap_add:
      - IPC_LOCK

  rabbitmq:
    image: rabbitmq:3.9.14-management
    container_name: spring-cloud-config-demo-rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
